CC=gcc
CFLAGS=-I.

parallel_min_max : utils.o find_min_max utils.h find_min_max.h
	$(CC) -o paral -std=c99 utils.o find_min_max.o parallel_min_max.c -lm $(CFLAGS)

utils.o : utils.h
	$(CC) -o utils.o -c utils.c $(CFLAGS)

find_min_max : utils.h find_min_max.h
	$(CC) -o find_min_max.o -c find_min_max.c $(CFLAGS)

clean :
	rm utils.o find_min_max.o paral -f 2> /dev/null